# Generated by Django 3.2.10 on 2022-04-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20220412_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler_db',
            name='status',
            field=models.CharField(max_length=1, verbose_name='is active'),
        ),
    ]
