# Generated by Django 3.2.10 on 2022-04-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_scheduler_db_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduler_db',
            options={},
        ),
    ]
