# Generated by Django 3.2.10 on 2022-05-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20220421_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1, verbose_name='is active')),
                ('date_begin', models.DateTimeField(verbose_name='date_begin')),
                ('date_end', models.DateTimeField(verbose_name='date_end')),
                ('comment', models.CharField(max_length=300, verbose_name='comment')),
                ('current_employee_name', models.CharField(max_length=100, verbose_name='doctor_name')),
                ('current_employee_lastname', models.CharField(max_length=100, verbose_name='Doctor_lastname')),
            ],
            options={
                'verbose_name': 'Расписание 0',
                'verbose_name_plural': 'Расписание',
            },
        ),
        migrations.RenameField(
            model_name='scheduler_db',
            old_name='Doctor_lastname',
            new_name='doctor_lastname',
        ),
    ]
