# Generated by Django 3.2.10 on 2022-05-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20220520_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('made_on', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='company_staff',
            name='current_employee_lastname',
            field=models.CharField(max_length=100, verbose_name='current_employee_lastname'),
        ),
        migrations.AlterField(
            model_name='scheduler_db',
            name='doctor_lastname',
            field=models.CharField(max_length=100, verbose_name='doctor_lastname'),
        ),
    ]
