# Generated by Django 3.2.13 on 2022-06-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_auto_20220622_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_staff',
            name='employer_phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='employer_phone_number'),
        ),
    ]
