# Generated by Django 3.2.13 on 2022-06-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_auto_20220623_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_staff',
            name='status',
            field=models.CharField(default='1', max_length=1, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='scheduler_db',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='scheduler_db',
            name='status',
            field=models.CharField(default='1', max_length=1, verbose_name='is active'),
        ),
    ]
