# Generated by Django 3.2.13 on 2022-06-23 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_auto_20220623_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler_db',
            name='staff_lastname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scheduler.company_staff'),
        ),
    ]
