# Generated by Django 3.2.13 on 2022-07-14 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_auto_20220623_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler_db',
            name='staff_lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='staff_lastname'),
            preserve_default=False,
        ),
    ]
