# Generated by Django 3.2.13 on 2022-10-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task_manager_work_days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateTimeField(verbose_name='date_begin')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='date_end')),
                ('profile_id', models.CharField(max_length=100, verbose_name='staff_name')),
                ('status', models.CharField(blank=True, max_length=1, null=True, verbose_name='is_working_day')),
            ],
            options={
                'verbose_name': 'Рабочее расписание',
            },
        ),
    ]
