# Generated by Django 3.2.13 on 2022-10-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_manager_work_days',
            name='profile_id',
            field=models.IntegerField(verbose_name='profile_id'),
        ),
    ]
