# Generated by Django 3.2.13 on 2022-12-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_auto_20221211_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_manager_work_days',
            name='date',
        ),
        migrations.AddField(
            model_name='task_manager_work_days',
            name='date_begin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_begin'),
        ),
        migrations.AddField(
            model_name='task_manager_work_days',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_end'),
        ),
    ]
