# Generated by Django 3.2.13 on 2023-01-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_task_manager_work_days_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_manager_work_days',
            name='user_id',
        ),
    ]
