# Generated by Django 3.2.13 on 2023-01-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_alter_task_manager_work_days_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_manager_work_days',
            name='user_id',
            field=models.IntegerField(verbose_name='user_id'),
        ),
    ]
