# Generated by Django 3.2.13 on 2023-02-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0010_alter_task_manager_work_days_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='description')),
                ('task_setting_date', models.DateField(verbose_name='task_setting_date')),
                ('due_date', models.DateField(verbose_name='due_date')),
                ('completed', models.BooleanField(default=False, verbose_name='completed')),
                ('task_author', models.CharField(max_length=200, verbose_name='task_author')),
                ('task_executor', models.CharField(max_length=200, verbose_name='task_executor')),
            ],
        ),
    ]
