# Generated by Django 3.2.13 on 2023-02-07 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0011_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Таблица задач'},
        ),
    ]
