# Generated by Django 3.2.13 on 2023-02-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0012_alter_task_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_setting_date',
        ),
        migrations.AddField(
            model_name='task',
            name='task_begin_date',
            field=models.DateField(blank=True, null=True, verbose_name='task_begin_date'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_making_date',
            field=models.DateField(blank=True, null=True, verbose_name='task_making_date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='completed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='due_date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='task_author'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_executor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='task_executor'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
