# Generated by Django 3.2.13 on 2023-02-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0013_auto_20230208_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='title'),
        ),
    ]
