# Generated by Django 3.2.13 on 2023-02-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0015_task_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='due_date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_begin_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='task_begin_date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_making_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='task_making_date'),
        ),
    ]
