# Generated by Django 3.2.10 on 2021-12-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
